universe = docker
docker_image = requiem98/geolocdock:v02
executable = /bin/python3
arguments = /home/amedeo_ranaldi/GeoLoc/main.py NOME_MODELLO
output = /home/amedeo_ranaldi/NOME_MODELLO/CondorLogs/out.$(ClusterId).$(ProcId)
error = /home/amedeo_ranaldi/NOME_MODELLO/CondorLogs/err.$(ClusterId).$(ProcId)
log = /home/amedeo_ranaldi/NOME_MODELLO/CondorLogs/log.$(ClusterId).$(ProcId)
request_cpus = 1
request_gpus = 1
request_memory = 32G
request_disk = 50G
+MountData1=FALSE
+MountData2=FALSE
+MountHomes=TRUE
queue 1

